### ISSUE TITLE
Dear Anisengupta,

### ISSUE THREAD

**Issue by vpassricha** [anisengupta/SIR-analysis-on-Covid-19#1]

**Comment by vpassricha** [comment]
You are doing well.
I read your code and saw the results. they are looking very good. I have one doubt that I did not find the code to calculate the forecast values. Can you explain the lines to find the forecast.
Thanking You

**Comment by anisengupta** [comment]
Hi @vpassricha 

Thank you for your message and hope that you are well. The code that I have used for this analysis to calculate forecasts of covid-19 can be found here: https://github.com/rajeshrinet/pyross. This is an excellent module designed to model epidemics in a country and I would recommend having a look there to see how the forecasts are calculated.

Thanks,
Aniruddha
